### ISSUE TITLE
Make scan timing and RatePack configurable

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/Node#382]
Reference MASQ-Project/MASQ-Node-issues#190 

Rows need to be added to the `CONFIG` table, and provisions made in `PersistentConfiguration`, `MASQNode-UIv2` and `masq`, and logic added in the code, to make configurable persistently and at runtime the following values:

Blockchain service URL (node_configurator_standard.rs)
`payment_suggested_after_sec`
`payment_grace_before_ban_sec`
`permanent_debt_allowed_gwei`
`balance_to_decrease_from_gwei`
`balance_decreases_for_sec`
`unban_when_balance_below_gwei` (accountant/mod.rs)
`routing_byte_rate`
`routing_service_rate`
`exit_byte_rate`
`exit_service_rate` (neighborhood.rs)
`payable_scan_interval`
`receivable_scan_interval`
`pending_payment_scan_interval` (accountant/mod.rs)

Historical note: the names in the code have the word "gwub" in place of the word "gwei" above; "gwub" was an attempt at a humorous combination of "gwei" (gigawei) and "SUB" (the original ERC-20 token used by Substratum). It was weak at best and is of no use now, so these names should be changed to something clearer.

Suggestion: the names of the values in the database (and preferably in the code as well) would be easier to understand if they included the unit of measurement at the end: for example, `permanent_debt_allowed_gwei` is much easier to understand than `routing_byte_rate`.

If the meanings of the values in accountant/mod.rs are not clear enough to complete this card, contact Dan for further information.

_Note: As a part of this card, we've reseted default values for the three group of parameters by which we de facto eliminated MASQ-Project/MASQ-Node-issues#550. We did so with that effect in mind._

**Comment by bertllll** [comment]
Test plan

Don't be scared by the length. It may be a playful time. Depends on how complex testing will be arranged, meaning whether in a network.

I'm putting forward 13 new configurable parameters. They are not exactly new, but they all used to be only unchangeable defaults. Now you have a chance to influence their values. All these parameters are stored in the database. Another important thing to note is that these parameters work only for static configuration, none can be set at run-time. This restriction may be lifted for some in the future but some may stay like so for ever. We don't have an exact picture right now. 

You will be bale to recognize that there are actually three groups of similar parameters. After various arguments pointing in both directions we decided to have these parameters always divided into a consistent set and to cope with them individually, it would blow up our code too much if we give you each to be set alone instead of having them in a set.

There is a common syntax for work with any of those sets. 
It always starts with the parameter set's name and continues with values delimited by the pipe mark "|". Every set has its own specific number of values or if you want a subset of parameters. So to be able to manipulate them you need to know some details of the subset. Here this guide shall help you know all you need; we'll decide later if we want to fill in some help messages (and what they should say).

To display the saved values you can use either --dump-config, but more ergonomically, also the configuration command.  

I suppose that also a new database migration should be under the test's scope.

Let's look at details.

_Note that all these parameters use quotation marks surrounding their set of values._

-------------

`--payment-curves "x|x|x|x|x|x"`

1.
 `balanceDecreasesForSec`: This interval begins after payment_suggested_after_sec for payables and after 
  payment_suggested_after_sec + payment_grace_before_ban for receivables. During the interval, the amount of a payable that is allowed
  to remain unpaid, or a receivable that doesn't cause a ban, decreases linearly from the balance_to_decrease_from to
  permanent_debt_allowed_gwei or unban-when_balance_below_gwei.

2.
 `balanceToDecreaseFromGwei`: Payables higher than this will be suggested for payment immediately upon passing
  the payment_suggested_after_sec age. Payables lower than this can stay unpaid longer. Receivables higher than this will never
  cause bans until they pass the payment_suggested_after + payment_grace_before_ban age. Receivables lower than this will survive longer
  without banning.

3.
 `paymentSuggestedAfterSec`: A really large payable can get this old before the Accountant's scanner suggests that it be paid. 

4.
 `paymentGraceBeforeBanSec`: A really large receivable can get as old as payment_suggested_after + payment_grace_before_ban before
  the Node that owes it will be banned.

5.
 `permanentDebtAllowedGwei`: Receivables this small and smaller will not cause bans no matter how old they get.

6.
 `unbanWhenBalanceBelowGwei`: When a delinquent Node has been banned, the receivables causing the ban must be paid below this level to
  cause them to be unbanned. In most cases, you'll want this to be set the same as permanent_debt_allowed_gwei.

----------------------

`--scan-intervals "x|x|x"` 

1.
 `pendingPayableSec`: Amount of seconds between two sequential cycles of scanning for payments that are marked as currently
  pending; the payments were sent to pay our debts, the payable. The purpose of this process is to confirm that the payment was written
  into the blockchain or failed.

2.
 `payableSec`: Amount of seconds between two sequential cycles of scanning aimed to find payable accounts of certain parameters; these 
  accounts are tracked on behalf of our creditors. If they qualify by enough big significance of time or money amount we have the debt be
  paid by sending a transaction to the creditor in question.

3.
 `receivableSec`: Amount of seconds between two sequential cycles of scanning for payments on the blockchain that have been sent
  by our creditors to us, they pay for our services this way.   
  
  ----------------
  
`--rate-pack "x|x|x|x"`

1. `routingByteRate`: This parameter indicates an amount of MASQ demanded to process 1 byte of routed payload while the Node is a common
  relay Node.

2. `routingServiceRate`: This parameter indicates an amount of MASQ demanded to provide services, unpacking and repacking 1 CORES
  package, while the Node is a common relay Node.
  
3. `exitByteRate`: This parameter indicates an amount of MASQ demanded to process 1 byte of routed payload while the Node acts as
  the exit Node.

4. `exitServiceRate`: This parameter indicates an amount of MASQ demanded to provide services, unpacking and repacking 1 CORES
  package, while the Node acts as the exit Node.


----------------------------
Please let @Crazylegscrane and @kauri-hero determine some favorable values for some of those parameters which would be exciting to see set. 
My advice is that you may want to experiment with:

paymentSuggestedAfterSec - in order to see payments earlier
permanentDebtAllowedGwei - if you want to limit down how much you must consume before it's considered a big enough debt (but then you probably want to set 
unbanWhenBalanceBelowGwei to the same value)

You also can lower scan intervals to minutes instead of an hour like now.

What we had never tested until this card is changing values for the rate pack. So I suppose a certain part of this test could turn into an experiment with these. 
And the outcome, if reasoning, could affect decisions about choosing proper defaults. I know that Kauri's already prepared some defaults and I don't mean he should change it by all cases - I don't mind if they eventually stay like they are.

**Comment by bertllll** [comment]
Update: a request to test additional points.

This test might be strictly for CLI users. 

Look at Node's startup parameters given from the `setup` command and think about how correct the values are when it says "Default" at their statuses - you don't have to stay too long here, you can scan it over fast; most importantly check that the default chain is "polygon-mainnet" now. 
Also check out the output of the `configuration` command if it seems roughly understandable. 

Also please check help description that has been added for the new parameters.
The way to the help is along:

a) MASQNode --help (for the Node's binaries)
b) masq setup --help (for the masq's binaries)

In both cases you will see the same text.
